[package]
name = "osm_models"
version = "1.0.1"
authors = ["Jason Abbott <you@example.com>"]
edition = "2018"
license = "MIT"
homepage = ""
repository = "https://github.com/toba/osm-models-rs.git"
readme = "README.md"

[dependencies]
hashbrown = { version = "0.7", features = ["serde"] }
